providers:
  zhipu:
    enabled: true
    plan_type: max
    session_token: 863c9913afbd4f6fb4e204528f4f1eb3.EwZS7q3hfZWORguU
  xiaomi:
    enabled: true
    plan_type: standard
    session_token: cookie-preferences=%7B%22analytical%22%3Atrue%2C%22functional%22%3Atrue%7D;
      api-platform_serviceToken="yVHEDQlNiFT1WavLtPFne1ouWnCOnW52h4DsBTpf1dHspgQZNJraGk3lHr2YAnC5Z/zLDu0MzrOjD+/jPcgA37coXqc+hJNCiOBfQglMTG0BLOUdZkdckd/NbMYvnYra+NLKX0OUmsf1C27vkI0/DJkqmapPtIMqeHRYZISEC4xZSkLjPZhPVBikqfgWUozJ1z7f5r5zHfup2ad1IsLdAyM/Vxrl/kp0tpwhkWz1ZW9eJRcBtw/SiP9eUF81amdBBGHF0HEwxboackzm/bGc7LymKfuwz0PM6IWeSiBYdb8EcTp9rtZKZgm6owALQwF3XOISc/VUDc4bGTeqakKLBu3A+N1p94stB+eeKi9cPPk=";
      userId=10792162; api-platform_slh="p697Lpyct6DWxOWQ2fW7RK/fROM="; api-platform_ph="cUcZ0ujPrtl9uvLn3/uLVg=="
